name: GitHub Actions automation
on: 
   pull_request:
      branches:
          - 'develop'
jobs:
    LintingAction:
       runs-on: windows-latest
       steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v3
           with:
               node-version: 14
         - run: npm ci
         - run: npx lint-staged
